.TH "lib_quickAF/rc/Component Directory Reference" 3 "Thu Mar 25 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_quickAF/rc/Component Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBusyIndicator\&.qml\fP"
.br
.ti -1c
.RI "file \fBContent\&.qml\fP"
.br
.ti -1c
.RI "file \fBHeader\&.qml\fP"
.br
.ti -1c
.RI "file \fBMirror\&.qml\fP"
.br
.ti -1c
.RI "file \fBPlugin\&.qml\fP"
.br
.ti -1c
.RI "file \fBTextInput\&.qml\fP"
.br
.in -1c
