.TH "lib_quickAF/rc/Object Directory Reference" 3 "Fri Mar 26 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_quickAF/rc/Object Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBColorButtonObject\&.qml\fP"
.br
.ti -1c
.RI "file \fBTextObject\&.qml\fP"
.br
.ti -1c
.RI "file \fBUrlButtonObject\&.qml\fP"
.br
.in -1c
