.TH "lib_baseAF Directory Reference" 3 "Fri Mar 26 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBaccount\fP"
.br
.ti -1c
.RI "directory \fBbase\fP"
.br
.ti -1c
.RI "directory \fBinclude\fP"
.br
.ti -1c
.RI "directory \fBtemplate\fP"
.br
.ti -1c
.RI "directory \fBtool\fP"
.br
.in -1c
