.TH "lib_quickAF/src Directory Reference" 3 "Fri Mar 26 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_quickAF/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBguiApplication\&.cpp\fP"
.br
.ti -1c
.RI "file \fBguiPlugin\&.cpp\fP"
.br
.ti -1c
.RI "file \fBguiSize\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmenuModel\&.cpp\fP"
.br
.in -1c
