.TH "serverAF Directory Reference" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serverAF Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBserver\&.cpp\fP"
.br
.ti -1c
.RI "file \fBserver\&.h\fP"
.br
.in -1c
