.TH "lib_quickAF/rc/Base Directory Reference" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_quickAF/rc/Base Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApp\&.qml\fP"
.br
.ti -1c
.RI "file \fBMenu\&.qml\fP"
.br
.ti -1c
.RI "file \fBPlugin\&.qml\fP"
.br
.in -1c
