.TH "lib_baseAF/include/lib_baseAF/afAccountInfo.h" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afAccountInfo.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QDir>\fP
.br
\fC#include <QtCore/QJsonObject>\fP
.br
\fC#include <QtCore/QObject>\fP
.br
\fC#include <QtCore/QSharedPointer>\fP
.br
\fC#include <QtCore/QString>\fP
.br
\fC#include <AFbase/AfId>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAFaccount::Info\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFaccount\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< Info > \fBAFaccount::InfoPtr\fP"
.br
.ti -1c
.RI "typedef QList< InfoPtr > \fBAFaccount::InfoPtrList\fP"
.br
.ti -1c
.RI "typedef QSharedPointer< \fBAFaccount::Info\fP > \fBAccInfoPtr\fP"
.br
.ti -1c
.RI "typedef QList< \fBAccInfoPtr\fP > \fBAccInfoPtrList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QSharedPointer<\fBAFaccount::Info\fP> \fBAccInfoPtr\fP"

.PP
Definition at line 45 of file afAccountInfo\&.h\&.
.SS "typedef QList<\fBAccInfoPtr\fP> \fBAccInfoPtrList\fP"

.PP
Definition at line 46 of file afAccountInfo\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF base library from the source code\&.
