.TH "lib_baseAF/account/afAccountInfo.cpp" 3 "Fri Mar 26 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/account/afAccountInfo.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'afAccountInfo\&.h'\fP
.br
\fC#include <QtCore/QVariant>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDATE_TIME\fP   'yyyy\&.MM\&.dd hh:mm:ss'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DATE_TIME   'yyyy\&.MM\&.dd hh:mm:ss'"

.PP
Definition at line 4 of file afAccountInfo\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
