.TH "lib_baseAF/base/afAPI.cpp" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/base/afAPI.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'afAPI\&.h'\fP
.br
\fC#include <optional>\fP
.br
\fC#include <QtCore/QCoreApplication>\fP
.br
\fC#include 'afServerSettings\&.h'\fP
.br
\fC#include 'AfStorage'\fP
.br
\fC#include <QtCore/QByteArray>\fP
.br
\fC#include 'afAccountStorage\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAFapiPtr\fP \fBafAPI\fP ()"
.br
.ti -1c
.RI "QDataStream & \fBAFlib::operator<<\fP (QDataStream &d, const \fBAFlib::RequestType\fP &type)"
.br
.ti -1c
.RI "QDataStream & \fBAFlib::operator>>\fP (QDataStream &d, \fBAFlib::RequestType\fP &type)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAFapiPtr\fP afAPI ()"

.PP
Definition at line 233 of file afAPI\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF base library from the source code\&.
