.TH "lib_baseAF/include/lib_baseAF/afDir.h" 3 "Thu Mar 25 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afDir.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QDir>\fP
.br
\fC#include <QtCore/QObject>\fP
.br
\fC#include <QtCore/QStringList>\fP
.br
\fC#include <QtCore/QSharedPointer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAFlib::Dir\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< Dir > \fBAFlib::DirPtr\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDirPtr\fP \fBAFlib::afDir\fP ()"
.br
.ti -1c
.RI "\fBAFlib::DirPtr\fP \fBAFDir\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAFlib::DirPtr\fP AFDir ()"

.PP
Definition at line 243 of file afDir\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
