.TH "lib_baseAF/tool/afDir.cpp" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/tool/afDir.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QDebug>\fP
.br
\fC#include <QtCore/QCoreApplication>\fP
.br
\fC#include <QtCore/QStandardPaths>\fP
.br
\fC#include 'afDir\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTEST_RELEASE\fP   true"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDirPtr\fP \fBAFDir\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TEST_RELEASE   true"

.PP
Definition at line 9 of file afDir\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "\fBDirPtr\fP AFDir ()"

.PP
Definition at line 243 of file afDir\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
