.TH "lib_baseAF/base/afFunction.cpp" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/base/afFunction.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QDebug>\fP
.br
\fC#include 'afFunction\&.h'\fP
.br
\fC#include 'afSystem\&.h'\fP
.br
\fC#include <QtCore/QDateTime>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AF base library from the source code\&.
