.TH "lib_baseAF/include/lib_baseAF/afIdAccount.h" 3 "Fri Mar 26 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afIdAccount.h
.SH SYNOPSIS
.br
.PP
\fC#include 'afIdBit\&.h'\fP
.br
\fC#include 'afEnum\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAFlib::id::Account_bit\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.ti -1c
.RI " \fBAFlib::id\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Account_bit \fBAFlib::id::Acc_bit\fP"
.br
.ti -1c
.RI "typedef QList< Account_bit > \fBAFlib::id::AccList_b\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
