.TH "lib_baseAF/include/lib_baseAF/afId.h" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afId.h
.SH SYNOPSIS
.br
.PP
\fC#include 'afIdBit\&.h'\fP
.br
\fC#include 'afIdAccount\&.h'\fP
.br
\fC#include 'afIdOperate\&.h'\fP
.br
\fC#include 'afIdObject\&.h'\fP
.br
\fC#include 'afIdGlobalBit\&.h'\fP
.br
\fC#include 'afIdObjectTemplate\&.h'\fP
.br
\fC#include 'afIdHistory\&.h'\fP
.br
\fC#include 'AfTransferOperateList'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef id::Account_bit \fBAFlib::IdAccount_bit\fP"
.br
.ti -1c
.RI "typedef id::History \fBAFlib::IdHistory\fP"
.br
.ti -1c
.RI "typedef id::HistoryPtr \fBAFlib::IdHistoryPtr\fP"
.br
.ti -1c
.RI "typedef id::Global_bit \fBAFlib::IdGlobal_bit\fP"
.br
.ti -1c
.RI "typedef id::Object \fBAFlib::IdObject\fP"
.br
.ti -1c
.RI "typedef id::ObjectTemplate \fBAFlib::IdObjectTemplate\fP"
.br
.ti -1c
.RI "typedef id::Object_bit \fBAFlib::IdObject_bit\fP"
.br
.ti -1c
.RI "typedef id::ObjectPtr \fBAFlib::IdObjectPtr\fP"
.br
.ti -1c
.RI "typedef id::ObjectPtrV \fBAFlib::IdObjectPtrV\fP"
.br
.ti -1c
.RI "typedef id::Operate \fBAFlib::IdOperate\fP"
.br
.ti -1c
.RI "typedef id::OperatePtr \fBAFlib::IdOperatePtr\fP"
.br
.ti -1c
.RI "typedef id::OperatePtrList \fBAFlib::IdOperatePtrList\fP"
.br
.ti -1c
.RI "typedef transfer::Send \fBAFlib::TransferOperateSendList\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdAccount_bit\fP \fBAFIdAccount\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdHistory\fP \fBAFIdHistory\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdHistoryPtr\fP \fBAFIdHistoryPtr\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdGlobal_bit\fP \fBAFIdGlobal_bit\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdObject\fP \fBAFIdObject\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdObjectTemplate\fP \fBAFIdObjectTemplate\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdObject_bit\fP \fBAFIdObject_bit\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdObjectPtr\fP \fBAFIdObjectPtr\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdObjectPtrV\fP \fBAFIdObjectPtrV\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdOperate\fP \fBAFIdOperate\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdOperatePtr\fP \fBAFIdOperatePtr\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::IdOperatePtrList\fP \fBAFIdOperatePtrList\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::Attribute\fP \fBAFattribute\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::Compress\fP \fBAFcompress\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::id::AccList_b\fP \fBAFaccList_b\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::TransferOperateSendList\fP \fBAFTransferOperateSendList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBAFlib::id::AccList_b\fP \fBAFaccList_b\fP"

.PP
Definition at line 52 of file afId\&.h\&.
.SS "typedef \fBAFlib::Attribute\fP \fBAFattribute\fP"

.PP
Definition at line 49 of file afId\&.h\&.
.SS "typedef \fBAFlib::Compress\fP \fBAFcompress\fP"

.PP
Definition at line 50 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdAccount_bit\fP \fBAFIdAccount\fP"

.PP
Definition at line 33 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdGlobal_bit\fP \fBAFIdGlobal_bit\fP"

.PP
Definition at line 38 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdHistory\fP \fBAFIdHistory\fP"

.PP
Definition at line 35 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdHistoryPtr\fP \fBAFIdHistoryPtr\fP"

.PP
Definition at line 36 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdObject\fP \fBAFIdObject\fP"

.PP
Definition at line 39 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdObject_bit\fP \fBAFIdObject_bit\fP"

.PP
Definition at line 41 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdObjectPtr\fP \fBAFIdObjectPtr\fP"

.PP
Definition at line 42 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdObjectPtrV\fP \fBAFIdObjectPtrV\fP"

.PP
Definition at line 43 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdObjectTemplate\fP \fBAFIdObjectTemplate\fP"

.PP
Definition at line 40 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdOperate\fP \fBAFIdOperate\fP"

.PP
Definition at line 45 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdOperatePtr\fP \fBAFIdOperatePtr\fP"

.PP
Definition at line 46 of file afId\&.h\&.
.SS "typedef \fBAFlib::IdOperatePtrList\fP \fBAFIdOperatePtrList\fP"

.PP
Definition at line 47 of file afId\&.h\&.
.SS "typedef \fBAFlib::TransferOperateSendList\fP \fBAFTransferOperateSendList\fP"

.PP
Definition at line 53 of file afId\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF base library from the source code\&.
