.TH "lib_baseAF/include/lib_baseAF/afIdGlobalBit.h" 3 "Thu Mar 25 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afIdGlobalBit.h
.SH SYNOPSIS
.br
.PP
\fC#include 'afIdBit\&.h'\fP
.br
\fC#include 'afIdAccount\&.h'\fP
.br
\fC#include 'afIdObjectBit\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAFlib::id::Global_bit\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.ti -1c
.RI " \fBAFlib::id\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QList< Global_bit > \fBAFlib::id::GlobalList_bit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QDebug \fBoperator<<\fP (QDebug d, const \fBAFlib::id::Global_bit\fP &object)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDebug operator<< (QDebug d, const \fBAFlib::id::Global_bit\fP & object)"

.PP
Definition at line 33 of file afIdGlobalBit\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
