.TH "lib_baseAF/include/lib_baseAF/afIdObjectBit.h" 3 "Fri Mar 26 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afIdObjectBit.h
.SH SYNOPSIS
.br
.PP
\fC#include 'afIdBit\&.h'\fP
.br
\fC#include 'afIdAccount\&.h'\fP
.br
\fC#include <QtCore/QDebug>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAFlib::id::Object_bit\fP"
.br
.RI "The \fBFunction\fP class\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.ti -1c
.RI " \fBAFlib::id\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Object_bit \fBAFlib::id::Obj_bit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QDebug \fBoperator<<\fP (QDebug d, const \fBAFlib::id::Object_bit\fP &obj_b)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBAFlib::id::Object_bit\fP &left, const \fBAFlib::id::Object_bit\fP &right)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDebug operator<< (QDebug d, const \fBAFlib::id::Object_bit\fP & obj_b)"

.PP
Definition at line 49 of file afIdObjectBit\&.cpp\&.
.SS "bool operator== (const \fBAFlib::id::Object_bit\fP & left, const \fBAFlib::id::Object_bit\fP & right)\fC [inline]\fP"

.PP
Definition at line 106 of file afIdObjectBit\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
