.TH "lib_baseAF/base/afIdObjectTemplate.cpp" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/base/afIdObjectTemplate.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'afIdObjectTemplate\&.h'\fP
.br
\fC#include <AFaccount/AfAccountStorage>\fP
.br
\fC#include <AFbase/AfStorage>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
