.TH "lib_baseAF/include/lib_baseAF/afIdBit.h" 3 "Fri Mar 26 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afIdBit.h
.SH SYNOPSIS
.br
.PP
\fC#include <bitset>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <QtCore/QDataStream>\fP
.br
\fC#include <QtCore/QBuffer>\fP
.br
\fC#include <QtCore/QDebug>\fP
.br
\fC#include <QtCore/QSharedPointer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAFlib::id::TbitStruct< bitsize >\fP"
.br
.ti -1c
.RI "struct \fBAFlib::id::TbitStruct< bitsize >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.ti -1c
.RI " \fBAFlib::id\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<uint bsize> QDataStream & \fBoperator<<\fP (QDataStream &s, const \fBAFlib::id::TbitStruct\fP< bsize > &data)"
.br
.ti -1c
.RI "template<uint bsize> QDataStream & \fBoperator>>\fP (QDataStream &s, \fBAFlib::id::TbitStruct\fP< bsize > &data)"
.br
.ti -1c
.RI "template<typename T > QDataStream & \fBoperator<<\fP (QDataStream &s, const std::vector< QSharedPointer< T >> &list)"
.br
.ti -1c
.RI "template<typename T > QDataStream & \fBoperator>>\fP (QDataStream &s, std::vector< QSharedPointer< T >> &list)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<uint bsize> QDataStream & operator<< (QDataStream & s, const \fBAFlib::id::TbitStruct\fP< bsize > & data)"

.PP
Definition at line 166 of file afIdBit\&.h\&.
.SS "template<typename T > QDataStream& operator<< (QDataStream & s, const std::vector< QSharedPointer< T >> & list)"

.PP
Definition at line 189 of file afIdBit\&.h\&.
.SS "template<uint bsize> QDataStream & operator>> (QDataStream & s, \fBAFlib::id::TbitStruct\fP< bsize > & data)"

.PP
Definition at line 173 of file afIdBit\&.h\&.
.SS "template<typename T > QDataStream& operator>> (QDataStream & s, std::vector< QSharedPointer< T >> & list)"

.PP
Definition at line 204 of file afIdBit\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
