.TH "lib_baseAF/include/lib_baseAF/afIdObject.h" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afIdObject.h
.SH SYNOPSIS
.br
.PP
\fC#include 'afIdHistory\&.h'\fP
.br
\fC#include 'afIdObjectBit\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAFlib::id::Object\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.ti -1c
.RI " \fBAFlib::id\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< Object > \fBAFlib::id::ObjectPtr\fP"
.br
.ti -1c
.RI "typedef std::vector< ObjectPtr > \fBAFlib::id::ObjectPtrV\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QDebug \fBoperator<<\fP (QDebug d, const \fBAFlib::id::Object\fP &object)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBAFlib::id::ObjectPtr\fP ptr, const \fBAFlib::id::Object\fP &object)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBAFlib::id::ObjectPtr\fP l, const \fBAFlib::id::ObjectPtr\fP r)"
.br
.ti -1c
.RI "\fBAFlib::id::ObjectPtrV\fP & \fBoperator+=\fP (\fBAFlib::id::ObjectPtrV\fP &l, const \fBAFlib::id::ObjectPtrV\fP &r)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAFlib::id::ObjectPtrV\fP& operator+= (\fBAFlib::id::ObjectPtrV\fP & l, const \fBAFlib::id::ObjectPtrV\fP & r)"

.PP
Definition at line 307 of file afIdObject\&.cpp\&.
.SS "QDebug operator<< (QDebug d, const \fBAFlib::id::Object\fP & object)"

.PP
Definition at line 283 of file afIdObject\&.cpp\&.
.SS "bool operator== (const \fBAFlib::id::ObjectPtr\fP l, const \fBAFlib::id::ObjectPtr\fP r)"

.PP
Definition at line 302 of file afIdObject\&.cpp\&.
.SS "bool operator== (const \fBAFlib::id::ObjectPtr\fP ptr, const \fBAFlib::id::Object\fP & object)"

.PP
Definition at line 295 of file afIdObject\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
