.TH "lib_baseAF/base/afIdObjectBit.cpp" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/base/afIdObjectBit.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'afIdObjectBit\&.h'\fP
.br
\fC#include 'AfFunction'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDebug \fBoperator<<\fP (QDebug d, const \fBAFlib::id::Object_bit\fP &obj_b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDebug operator<< (QDebug d, const \fBAFlib::id::Object_bit\fP & obj_b)"

.PP
Definition at line 49 of file afIdObjectBit\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
