.TH "AFlib::transfer::answer::DPathObjectList" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFlib::transfer::answer::DPathObjectList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <afTransferOperateList\&.h>\fP
.PP
Inherits QList< Object >\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QStringList \fBdPath\fP"
.br
.ti -1c
.RI "\fBFileType\fP \fBfileType\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &stream, const \fBDPathObjectList\fP &data)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &stream, \fBDPathObjectList\fP &data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file afTransferOperateList\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & stream, const \fBDPathObjectList\fP & data)\fC [friend]\fP"

.PP
Definition at line 42 of file afTransferOperateList\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & stream, \fBDPathObjectList\fP & data)\fC [friend]\fP"

.PP
Definition at line 47 of file afTransferOperateList\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QStringList AFlib::transfer::answer::DPathObjectList::dPath"

.PP
Definition at line 36 of file afTransferOperateList\&.h\&.
.SS "\fBFileType\fP AFlib::transfer::answer::DPathObjectList::fileType"

.PP
Definition at line 37 of file afTransferOperateList\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
