.TH "AFlib::id::Global_bit" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFlib::id::Global_bit
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <afIdGlobalBit\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlobal_bit\fP (\fBAccount_bit\fP owner, \fBObject_bit\fP object)"
.br
.ti -1c
.RI "\fBGlobal_bit\fP (quint64 number)"
.br
.ti -1c
.RI "quint64 \fBtoNumber\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAccount_bit\fP \fBownerId\fP"
.br
.ti -1c
.RI "\fBObject_bit\fP \fBobjectId\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBGlobal_bit\fP &l, const \fBGlobal_bit\fP &r)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &s, const \fBGlobal_bit\fP &id)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &s, \fBGlobal_bit\fP &id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file afIdGlobalBit\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AFlib::id::Global_bit::Global_bit (\fBAccount_bit\fP owner, \fBObject_bit\fP object)"

.PP
Definition at line 4 of file afIdGlobalBit\&.cpp\&.
.SS "AFlib::id::Global_bit::Global_bit (quint64 number)"

.PP
Definition at line 10 of file afIdGlobalBit\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "quint64 AFlib::id::Global_bit::toNumber () const"

.PP
Definition at line 16 of file afIdGlobalBit\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & s, const \fBGlobal_bit\fP & id)\fC [friend]\fP"

.PP
Definition at line 22 of file afIdGlobalBit\&.cpp\&.
.SS "bool operator== (const \fBGlobal_bit\fP & l, const \fBGlobal_bit\fP & r)\fC [friend]\fP"

.PP
Definition at line 29 of file afIdGlobalBit\&.h\&.
.SS "QDataStream& operator>> (QDataStream & s, \fBGlobal_bit\fP & id)\fC [friend]\fP"

.PP
Definition at line 27 of file afIdGlobalBit\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBObject_bit\fP AFlib::id::Global_bit::objectId"

.PP
Definition at line 22 of file afIdGlobalBit\&.h\&.
.SS "\fBAccount_bit\fP AFlib::id::Global_bit::ownerId"

.PP
Definition at line 21 of file afIdGlobalBit\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
