.TH "AFlib::Setting" 3 "Fri Mar 26 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFlib::Setting
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <afSetting\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetting\fP (QObject *parent=nullptr)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::optional< QVariant > \fBvalue\fP (const QString &key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file afSetting\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AFlib::Setting::Setting (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line 4 of file afSetting\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::optional< QVariant > AFlib::Setting::value (const QString & key)\fC [static]\fP"

.PP
Definition at line 9 of file afSetting\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
