.TH "AFlib::transfer::answer" 3 "Thu Mar 25 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFlib::transfer::answer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDPathObjectList\fP"
.br
.ti -1c
.RI "struct \fBObject\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &stream, const \fBAFlib::transfer::answer::Object\fP &data)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &stream, \fBAFlib::transfer::answer::Object\fP &data)"
.br
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &stream, const \fBAFlib::transfer::answer::DPathObjectList\fP &data)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &stream, \fBAFlib::transfer::answer::DPathObjectList\fP &data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& AFlib::transfer::answer::operator<< (QDataStream & stream, const \fBAFlib::transfer::answer::DPathObjectList\fP & data)"

.PP
Definition at line 42 of file afTransferOperateList\&.cpp\&.
.SS "QDataStream& AFlib::transfer::answer::operator<< (QDataStream & stream, const \fBAFlib::transfer::answer::Object\fP & data)"

.PP
Definition at line 32 of file afTransferOperateList\&.cpp\&.
.SS "QDataStream& AFlib::transfer::answer::operator>> (QDataStream & stream, \fBAFlib::transfer::answer::DPathObjectList\fP & data)"

.PP
Definition at line 47 of file afTransferOperateList\&.cpp\&.
.SS "QDataStream& AFlib::transfer::answer::operator>> (QDataStream & stream, \fBAFlib::transfer::answer::Object\fP & data)"

.PP
Definition at line 37 of file afTransferOperateList\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
