.TH "AFlib::Storage::SingleStorage" 3 "Thu Mar 25 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFlib::Storage::SingleStorage
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QDateTime \fBlastChange\fP"
.br
.ti -1c
.RI "\fBIdObject_bit\fP \fBid\fP"
.br
.ti -1c
.RI "QStringList \fBdPath\fP"
.br
.ti -1c
.RI "\fBFileType\fP \fBfileType\fP"
.br
.ti -1c
.RI "QList< \fBid::Global_bit\fP > \fBlocalSharedList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file afStorage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "QStringList AFlib::Storage::SingleStorage::dPath"

.PP
Definition at line 67 of file afStorage\&.h\&.
.SS "\fBFileType\fP AFlib::Storage::SingleStorage::fileType"

.PP
Definition at line 68 of file afStorage\&.h\&.
.SS "\fBIdObject_bit\fP AFlib::Storage::SingleStorage::id"

.PP
Definition at line 66 of file afStorage\&.h\&.
.SS "QDateTime AFlib::Storage::SingleStorage::lastChange"

.PP
Definition at line 65 of file afStorage\&.h\&.
.SS "QList<\fBid::Global_bit\fP> AFlib::Storage::SingleStorage::localSharedList"

.PP
Definition at line 70 of file afStorage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
