.TH "AFlib::transfer" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFlib::transfer
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBanswer\fP"
.br
.ti -1c
.RI " \fBsend\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnswer\fP"
.br
.ti -1c
.RI "class \fBSend\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
