.TH "AFlib::Storage::AccountStorage" 3 "Thu Mar 25 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFlib::Storage::AccountStorage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddPlugin\fP (quint8 id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBid::Account_bit\fP \fBaccountBit\fP"
.br
.ti -1c
.RI "std::vector< \fBPluginStorage\fP > \fBpluginList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 80 of file afStorage\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Storage::AccountStorage::addPlugin (quint8 id)"

.PP
Definition at line 554 of file afStorage\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBid::Account_bit\fP AFlib::Storage::AccountStorage::accountBit"

.PP
Definition at line 81 of file afStorage\&.h\&.
.SS "std::vector<\fBPluginStorage\fP> AFlib::Storage::AccountStorage::pluginList"

.PP
Definition at line 83 of file afStorage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
