.TH "AFlib::Storage::PluginStorage" 3 "Thu Mar 25 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFlib::Storage::PluginStorage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddSingle\fP (QStringList dPath, \fBFileType\fP fileType, QDateTime time, \fBIdObject_bit\fP id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "quint8 \fBpluginId\fP"
.br
.ti -1c
.RI "std::vector< \fBSingleStorage\fP > \fBidList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file afStorage\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Storage::PluginStorage::addSingle (QStringList dPath, \fBFileType\fP fileType, QDateTime time, \fBIdObject_bit\fP id)"

.PP
Definition at line 540 of file afStorage\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBSingleStorage\fP> AFlib::Storage::PluginStorage::idList"

.PP
Definition at line 76 of file afStorage\&.h\&.
.SS "quint8 AFlib::Storage::PluginStorage::pluginId"

.PP
Definition at line 74 of file afStorage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
