.TH "AFquick::MenuSingle" 3 "Thu Mar 25 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFquick::MenuSingle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menuModel\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBiconPath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file menuModel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "QString AFquick::MenuSingle::iconPath"

.PP
Definition at line 11 of file menuModel\&.h\&.
.SS "QString AFquick::MenuSingle::name"

.PP
Definition at line 10 of file menuModel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
