.TH "AFquick" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFquick
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGuiApplication\fP"
.br
.ti -1c
.RI "class \fBGuiPlugin\fP"
.br
.ti -1c
.RI "class \fBGuiSize\fP"
.br
.ti -1c
.RI "class \fBMenuModel\fP"
.br
.ti -1c
.RI "struct \fBMenuSingle\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< \fBGuiPlugin\fP > \fBGuiPluginPtr\fP"
.br
.ti -1c
.RI "typedef QSharedPointer< \fBGuiSize\fP > \fBGuiSizePtr\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGuiSizePtr\fP \fBguiSize\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QSharedPointer<\fBGuiPlugin\fP> \fBAFquick::GuiPluginPtr\fP"

.PP
Definition at line 10 of file guiPlugin\&.h\&.
.SS "typedef QSharedPointer<\fBGuiSize\fP> \fBAFquick::GuiSizePtr\fP"

.PP
Definition at line 9 of file guiSize\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBAFquick::GuiSizePtr\fP AFquick::guiSize ()"

.PP
Definition at line 57 of file guiSize\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
