.TH "lib_baseAF/include/lib_baseAF/afSetting.h" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afSetting.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAFlib::Setting\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< Setting > \fBAFlib::SettingPtr\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
