.TH "lib_baseAF/tool/afSetting.cpp" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/tool/afSetting.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'afSetting\&.h'\fP
.br
\fC#include <QtCore/QVariant>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AF base library from the source code\&.
