.TH "lib_baseAF/tool/afServerSettings.cpp" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/tool/afServerSettings.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'lib_baseAF/afServerSettings\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAFlib::ServerSettingPtr\fP \fBafServerSettings\fP (QObject *parent)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAFlib::ServerSettingPtr\fP \fBp_serverSettingsPtr\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAFlib::ServerSettingPtr\fP afServerSettings (QObject * parent)"

.PP
Definition at line 38 of file afServerSettings\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBAFlib::ServerSettingPtr\fP p_serverSettingsPtr"

.PP
Definition at line 3 of file afServerSettings\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF base library from the source code\&.
