.TH "lib_baseAF/include/lib_baseAF/afServerSettings.h" 3 "Fri Mar 26 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afServerSettings.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QObject>\fP
.br
\fC#include <QtCore/QMap>\fP
.br
\fC#include <QtCore/QSharedPointer>\fP
.br
\fC#include <QtCore/QDateTime>\fP
.br
\fC#include <QtCore/QSettings>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAFlib::ServerSetting\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< ServerSetting > \fBAFlib::ServerSettingPtr\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ServerSettingPtr \fBAFlib::afServerSettings\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBAFlib::ServerSettingPtr\fP \fBafServerSettings\fP (QObject *parent=nullptr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAFlib::ServerSettingPtr\fP afServerSettings (QObject * parent = \fCnullptr\fP)"

.PP
Definition at line 38 of file afServerSettings\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
