.TH "lib_baseAF/include/lib_baseAF/afStorage.h" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afStorage.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QDateTime>\fP
.br
\fC#include 'afDir\&.h'\fP
.br
\fC#include 'afId\&.h'\fP
.br
\fC#include <QtCore/QCoreApplication>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAFlib::Storage\fP"
.br
.ti -1c
.RI "struct \fBAFlib::Storage::SingleStorage\fP"
.br
.ti -1c
.RI "struct \fBAFlib::Storage::PluginStorage\fP"
.br
.ti -1c
.RI "struct \fBAFlib::Storage::AccountStorage\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< Storage > \fBAFlib::StoragePtr\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::Storage\fP \fBAFStorage\fP"
.br
.ti -1c
.RI "typedef \fBAFlib::StoragePtr\fP \fBAFStoragePtr\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBStoragePtr\fP \fBAFlib::afStorage\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBAFlib::Storage\fP \fBAFStorage\fP"

.PP
Definition at line 102 of file afStorage\&.h\&.
.SS "typedef \fBAFlib::StoragePtr\fP \fBAFStoragePtr\fP"

.PP
Definition at line 103 of file afStorage\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
