.TH "lib_baseAF/tool/afStorage.cpp" 3 "Thu Mar 25 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/tool/afStorage.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'afStorage\&.h'\fP
.br
\fC#include <QtCore/QDebug>\fP
.br
\fC#include 'lib_baseAF/afFile\&.h'\fP
.br
\fC#include 'afTransferOperateList\&.h'\fP
.br
\fC#include 'afAccountStorage\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static \fBStoragePtr\fP \fBstorage_ptr\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBStoragePtr\fP storage_ptr\fC [static]\fP"

.PP
Definition at line 8 of file afStorage\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
