.TH "lib_baseAF/include/lib_baseAF/afSystem.h" 3 "Thu Mar 25 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afSystem.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QObject>\fP
.br
\fC#include <QtCore/QString>\fP
.br
\fC#include 'afEnum\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAFlib::System\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
