.TH "lib_baseAF/include/lib_baseAF/afTransferOperateList.h" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_baseAF/include/lib_baseAF/afTransferOperateList.h
.SH SYNOPSIS
.br
.PP
\fC#include 'afIdAccount\&.h'\fP
.br
\fC#include 'afIdObjectBit\&.h'\fP
.br
\fC#include 'afIdOperate\&.h'\fP
.br
\fC#include 'afIdObject\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAFlib::transfer::answer::Object\fP"
.br
.ti -1c
.RI "struct \fBAFlib::transfer::answer::DPathObjectList\fP"
.br
.ti -1c
.RI "class \fBAFlib::transfer::Answer\fP"
.br
.ti -1c
.RI "struct \fBAFlib::transfer::send::Operates\fP"
.br
.ti -1c
.RI "struct \fBAFlib::transfer::send::Objects\fP"
.br
.ti -1c
.RI "class \fBAFlib::transfer::Send\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFlib\fP"
.br
.ti -1c
.RI " \fBAFlib::transfer\fP"
.br
.ti -1c
.RI " \fBAFlib::transfer::send\fP"
.br
.ti -1c
.RI " \fBAFlib::transfer::answer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AF base library from the source code\&.
