.TH "lib_quickAF/src/guiApplication.cpp" 3 "Wed Apr 7 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_quickAF/src/guiApplication.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'guiApplication\&.h'\fP
.br
\fC#include 'guiSize\&.h'\fP
.br
\fC#include <QtQml/QQmlContext>\fP
.br
\fC#include <QtQuick/QQuickItem>\fP
.br
\fC#include <AFaccount/AfAccountStorage>\fP
.br
\fC#include <AFbase/AfStorage>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QUrl \fBm_defaultQmlUrl\fP ('qrc:/AFquick/Base/App\&.qml')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QUrl m_defaultQmlUrl ('qrc:/AFquick/Base/App\&.qml')"

.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
