.TH "lib_quickAF/include/lib_quickAF/guiApplication.h" 3 "Fri Mar 26 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_quickAF/include/lib_quickAF/guiApplication.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui/QGuiApplication>\fP
.br
\fC#include <QtQuick/QQuickView>\fP
.br
\fC#include 'guiPlugin\&.h'\fP
.br
\fC#include 'menuModel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAFquick::GuiApplication\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFquick\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBAFquick::GuiApplication\fP \fBAFguiApplication\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBAFquick::GuiApplication\fP \fBAFguiApplication\fP"

.PP
Definition at line 76 of file guiApplication\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
