.TH "lib_quickAF/src/guiPlugin.cpp" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_quickAF/src/guiPlugin.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'guiPlugin\&.h'\fP
.br
\fC#include 'guiApplication\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AF base library from the source code\&.
