.TH "lib_quickAF/include/lib_quickAF/guiSize.h" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_quickAF/include/lib_quickAF/guiSize.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QPoint>\fP
.br
\fC#include <QtCore/QObject>\fP
.br
\fC#include <QtCore/QSharedPointer>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAFquick::GuiSize\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFquick\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QSharedPointer< GuiSize > \fBAFquick::GuiSizePtr\fP"
.br
.ti -1c
.RI "typedef \fBAFquick::GuiSize\fP \fBAFguiSize\fP"
.br
.ti -1c
.RI "typedef \fBAFquick::GuiSizePtr\fP \fBAFguiSizePtr\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "GuiSizePtr \fBAFquick::guiSize\fP ()"
.br
.ti -1c
.RI "\fBAFguiSizePtr\fP \fBafGuiSize\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBAFquick::GuiSize\fP \fBAFguiSize\fP"

.PP
Definition at line 43 of file guiSize\&.h\&.
.SS "typedef \fBAFquick::GuiSizePtr\fP \fBAFguiSizePtr\fP"

.PP
Definition at line 44 of file guiSize\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBAFguiSizePtr\fP afGuiSize ()"

.PP
Definition at line 52 of file guiSize\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF base library from the source code\&.
