.TH "lib_quickAF/src/guiSize.cpp" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_quickAF/src/guiSize.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'guiSize\&.h'\fP
.br
\fC#include <QtGui/QGuiApplication>\fP
.br
\fC#include <AFbase/AfSystem>\fP
.br
\fC#include <QtGui/QScreen>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBAFguiSizePtr\fP \fBafGuiSize\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBAFguiSizePtr\fP \fBafGuiSizePtr\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBAFguiSizePtr\fP afGuiSize ()"

.PP
Definition at line 52 of file guiSize\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBAFguiSizePtr\fP afGuiSizePtr"

.PP
Definition at line 6 of file guiSize\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF base library from the source code\&.
