.TH "lib_quickAF/include/lib_quickAF/menuModel.h" 3 "Fri Mar 26 2021" "AF library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib_quickAF/include/lib_quickAF/menuModel.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QAbstractListModel>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAFquick::MenuSingle\fP"
.br
.ti -1c
.RI "class \fBAFquick::MenuModel\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAFquick\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBAFquick::MenuModel\fP \fBAFquickMenuModel\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBAFquick::MenuModel\fP \fBAFquickMenuModel\fP"

.PP
Definition at line 49 of file menuModel\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AF library from the source code\&.
