.TH "serverAF/server.cpp" 3 "Wed Apr 7 2021" "AF base library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serverAF/server.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'server\&.h'\fP
.br
\fC#include <AfAPI>\fP
.br
\fC#include <AFaccountLib>\fP
.br
\fC#include <AFbaseLib>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AF base library from the source code\&.
